
colleges:
  - name: shasun
    enabled: true
    branch: shasun-college
    brandingPaths:
      - public/logo.svg
      - public/logo-dark.svg
    mirrorRepo: https://github.com/shasun-honesty/honesty-shop.git
    webhookUrl: https://chat.googleapis.com/v1/spaces/AAQAoWicARw/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=nhH3Z6qWgPvEPuk8Jg9tDSh5XtKfFzF9YrD0qGC7ccs

  - name: alpha
    enabled: true
    branch: alpha-college
    brandingPaths:
      - public/logo.svg
      - public/logo-dark.svg
    mirrorRepo: https://github.com/alpha-org/alpha-shop.git
    webhookUrl: https://hooks.alphacollege.edu/notify
