
// Main Configuration - Consolidated from modular config files
import { APP_CONFIG } from './app';
import { BRANDING_CONFIG } from './branding';
import { IMAGES_CONFIG } from './images';
import { FORMS_CONFIG } from './forms';
import { MESSAGES_CONFIG } from './messages';
import { SYSTEM_CONFIG } from './system';
import { SUPABASE_CONFIG } from './supabase';

// Main CONFIG object
export const CONFIG = {
  APP: APP_CONFIG,
  BRANDING: BRANDING_CONFIG,
  SUPABASE: SUPABASE_CONFIG,
  IMAGES: IMAGES_CONFIG,
  FORMS: FORMS_CONFIG,
  MESSAGES: MESSAGES_CONFIG,
  SYSTEM: SYSTEM_CONFIG,
  ADMIN: {
    ACCESS_NOTE: "Super Admin Access: Check with Radhika",
  },
};

// Export utilities
export { getSupabaseConfig, getLogoUrl, generateThemeCSS, loadImageWithRetry, validateConfig } from './utils';

// Backward compatibility - flattened export (maintaining existing API)
export const WHITELABEL_CONFIG = {
  // App Identity
  APP_NAME: CONFIG.APP.NAME,
  APP_TAGLINE: CONFIG.APP.TAGLINE,
  APP_SUBTITLE: CONFIG.APP.SUBTITLE,
  APP_DESCRIPTION: CONFIG.APP.DESCRIPTION,
  
  // Branding - properly nested
  BRANDING: CONFIG.BRANDING,
  COLLEGE_NAME: CONFIG.BRANDING.COLLEGE_NAME,
  PORTAL_NAME: CONFIG.BRANDING.PORTAL_NAME,
  COLORS: CONFIG.BRANDING.COLORS,
  
  // Images
  IMAGES: CONFIG.IMAGES,
  LOGO_URL: CONFIG.IMAGES.COLLEGE_LOGO,
  FAVICON_URL: CONFIG.IMAGES.FAVICON,
  COLLEGE_LOGO_FALLBACK: CONFIG.IMAGES.COLLEGE_LOGO_FALLBACK,
  BADGE_IMAGES: CONFIG.IMAGES.BADGE_IMAGES,
  
  // Forms - flattened for easier access
  FORM_LABELS: CONFIG.FORMS.LABELS,
  FORM_PLACEHOLDERS: CONFIG.FORMS.PLACEHOLDERS,
  LABELS: CONFIG.FORMS.LABELS,
  PLACEHOLDERS: CONFIG.FORMS.PLACEHOLDERS,
  SHIFT_OPTIONS: CONFIG.FORMS.SHIFT_OPTIONS,
  ROLE_OPTIONS: CONFIG.FORMS.ROLE_OPTIONS,
  
  // Messages - flattened structure
  AUTH_MESSAGES: CONFIG.MESSAGES.AUTH,
  NAVIGATION: CONFIG.MESSAGES.NAVIGATION,
  PRODUCT_MESSAGES: CONFIG.MESSAGES.PRODUCTS,
  ERROR_MESSAGES: CONFIG.MESSAGES.ERRORS,
  LOADING_STATES: CONFIG.MESSAGES.LOADING,
  SUCCESS_MESSAGES: CONFIG.MESSAGES.SUCCESS,
  
  // System
  DEFAULT_POINTS: CONFIG.SYSTEM.DEFAULT_POINTS,
  PERFORMANCE: CONFIG.SYSTEM.PERFORMANCE,
  SECURITY: CONFIG.SYSTEM.SECURITY,
  ISO_COMPLIANCE: CONFIG.SYSTEM.ISO_COMPLIANCE,
  
  // Admin
  ADMIN_ACCESS_NOTE: CONFIG.ADMIN.ACCESS_NOTE,
  
  // Supabase
  SUPABASE: CONFIG.SUPABASE,
};
