
// System Settings Configuration
export const SYSTEM_CONFIG = {
  DEFAULT_POINTS: 100,
  PERFORMANCE: {
    CACHE_TIMEOUT: 5 * 60 * 1000, // 5 minutes
    MAX_LOGIN_ATTEMPTS: 5,
    SESSION_TIMEOUT: 24 * 60 * 60 * 1000, // 24 hours
    IMAGE_RETRY_ATTEMPTS: 3,
    IMAGE_RETRY_DELAY: 1000, // 1 second
    ENABLE_CACHING: true,
  },
  SECURITY: {
    ENABLE_CSRF_PROTECTION: true,
    ENABLE_XSS_PROTECTION: true,
    ENABLE_RATE_LIMITING: true,
    SESSION_VALIDATION_INTERVAL: 5 * 60 * 1000, // 5 minutes
    AUDIT_LOG_RETENTION: 90 * 24 * 60 * 60 * 1000, // 90 days
  },
  ISO_COMPLIANCE: {
    ENABLE_AUDIT_LOGGING: true,
    ENABLE_PERFORMANCE_MONITORING: true,
    ENABLE_SECURITY_MONITORING: true,
    ENABLE_QUALITY_ASSURANCE: true,
    COMPLIANCE_CHECK_INTERVAL: 24 * 60 * 60 * 1000, // 24 hours
  },
};
