name: Mirror shasun-college to Shasun Repo

on:
  push:
    branches:
      - shasun-college

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: shasun-college

      - name: Configure Git
        run: |
          git config --global user.name "Kannan"
          git config --global user.email "kannangates@gmail.com"

      - name: Push to Shasun repo
        env:
          COLLEGE_REPO_TOKEN: ${{ secrets.COLLEGE_REPO_TOKEN }}
        run: |
          git remote add shasun https://x-access-token:${COLLEGE_REPO_TOKEN}@github.com/shasun-honesty/honesty-shop.git
          git push --force shasun shasun-college:main

          echo "✅ Synced shasun-college → Shasun main branch"
