name: Mirror to College Repository

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "Kannan"
        git config --global user.email "your-email@example.com"

    - name: Add college remote and force push
      env:
        COLLEGE_REPO_TOKEN: ${{ secrets.COLLEGE_REPO_TOKEN }}
        COLLEGE_REPO_URL: ${{ vars.COLLEGE_REPO_URL || 'https://github.com/your-org/college-honesty-shop.git' }}
      run: |
        # Add college repository as remote
        git remote add college https://x-access-token:${COLLEGE_REPO_TOKEN}@${COLLEGE_REPO_URL#https://}
        
        # Force push to college repository
        git push college main --force
        
        echo "✅ Successfully mirrored code to college repository"