name: Auto Sync & Mirror to College Repos

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load college config
        id: set-matrix
        run: |
          config=$(cat .github/college-sync-config.yml)
          echo "matrix=$(echo \"$config\" | yq -o json | jq -c '.colleges | map(select(.enabled == true))')" >> $GITHUB_OUTPUT

  sync-and-mirror:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.COLLEGE_REPO_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch and checkout target branch
        run: |
          git fetch origin ${{ matrix.branch }} || git checkout -b ${{ matrix.branch }}
          git checkout ${{ matrix.branch }}

      - name: Get last commit message
        id: last_commit
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Merge from main and exclude branding
        run: |
          git merge origin/main --no-commit || echo "No changes"
          for file in ${{ join(matrix.brandingPaths, ' ') }}; do
            echo "Excluding $file"
            git restore --staged "$file" || true
            git restore "$file" || true
          done
          git commit -m "🔁 Auto-merged from main (branding preserved)" || echo "No new commit"

      - name: Push to internal college branch
        run: |
          git push origin ${{ matrix.branch }} --force

      - name: Mirror to college GitHub repo
        env:
          COLLEGE_REPO_URL: ${{ matrix.mirrorRepo }}
          COLLEGE_REPO_TOKEN: ${{ secrets.COLLEGE_REPO_TOKEN }}
        run: |
          CLEAN_REPO_URL="${COLLEGE_REPO_URL/https:\/\//}"
          echo "🔁 Pushing to: $CLEAN_REPO_URL"
          git remote add college https://x-access-token:${COLLEGE_REPO_TOKEN}@${CLEAN_REPO_URL}
          git push college ${{ matrix.branch }}:main --force

      - name: Notify Success
        if: success()
        run: |
          curl -X POST "${{ matrix.webhookUrl }}" \
          -H 'Content-Type: application/json' \
          -d '{
            "text": "✅ *Sync Success* for *${{ matrix.name }}* → `${{ matrix.branch }}`\n*Last Commit:* ${{ steps.last_commit.outputs.message }}\nTimestamp: $(date -u +%FT%TZ)"
          }'

      - name: Notify Failure
        if: failure()
        run: |
          curl -X POST "${{ matrix.webhookUrl }}" \
          -H 'Content-Type: application/json' \
          -d '{
            "text": "❌ *Sync Failed* for *${{ matrix.name }}* → `${{ matrix.branch }}`\nPlease check GitHub Actions logs.\nTimestamp: $(date -u +%FT%TZ)"
          }'

      - name: Final Log
        run: |
          echo "✅ Synced ${{ matrix.branch }} → ${{ matrix.mirrorRepo }} main branch"
